### ISSUE TITLE
Pytorch的windows环境配置问题

### ISSUE THREAD

**Issue by LeoLRH** [sharedeeply/DeepLearning-StartKit#1]
![ut4f18m 9vy x8wp18fiq p](https://user-images.githubusercontent.com/38356920/47229077-68996180-d3f9-11e8-8240-62445de8afaa.png)
老师我的torch是安装好的但是就是bu不明白在windows下是什么原因

**Comment by L1aoXingyu** [comment]
你 import torch 能 import 吗

**Comment by LeoLRH** [comment]
可以的
![fll2tudtlfif 9 0vlv 61](https://user-images.githubusercontent.com/38356920/47249308-b7201d80-d444-11e8-8964-8930b221183a.png)

**Comment by LeoLRH** [comment]
![image](https://user-images.githubusercontent.com/38356920/47250419-3ddbf700-d453-11e8-9411-b6595974a1ad.png)
主要是老师我已经检查了torch环境是没问题但是具体问题出现这样的问题啦

**Comment by LeoLRH** [comment]
就是图像分类的baseline里出现的这样的问题

**Comment by L1aoXingyu** [comment]
你在 cmd 里面运行试试，运行 python3 train.py

**Comment by LeoLRH** [comment]
![rl1 1nv 8y m _ zx4a znx](https://user-images.githubusercontent.com/38356920/47250554-85638280-d455-11e8-8a52-9334b8a7102e.png)
这是我的运行结果
![image](https://user-images.githubusercontent.com/38356920/47250563-99a77f80-d455-11e8-9790-5032d6a43a2c.png)
这是我pip list
所以我推测这个不是torch的问题
可不可能是python解释器的问题应该用conda里面的python解释器呢？

**Comment by L1aoXingyu** [comment]
你是在conda的新环境里面装的吗，你需要激活环境，另外这个问题你可以去网上找找，就是 DLL load failed

**Comment by LeoLRH** [comment]
老师问题已解决
提供一个windows的pytorch问题解决solution
https://blog.csdn.net/dia323/article/details/80732498
谢谢老师讲解

**Comment by LeoLRH** [comment]
但是在conda运行那个脚本还是不行

**Comment by LeoLRH** [comment]
有点迷但是不影响学习

**Comment by L1aoXingyu** [comment]
那个脚本是在cmd里面直接运行，可能windows有问题吧，你直接手动解压数据，然后运行 preprocess.py

**Comment by LeoLRH** [comment]
是的老师我运行脚本是在cmd上运行的，我是想如果我在notebook上运行那段train.py代码为什么是不行的
呢？

**Comment by L1aoXingyu** [comment]
你就在 cmd 上运行 train.py，不要再notebook里运行

**Comment by LeoLRH** [comment]
issue结束，谢谢老师

**Comment by L1aoXingyu** [comment]
那个脚本是在cmd里面直接运行，可能windows有问题吧，你直接手动解压数据，然后运行 preprocess.py

On Oct 20, 2018, at 11:20, Ruihang Liu <notifications@github.com> wrote:


但是在conda运行那个脚本还是不行
